### ISSUE TITLE
PdeInterfaces

### ISSUE THREAD

**Issue by azev77** [JuliaPDE/SurveyofPDEPackages#37]
@vpuri3
https://github.com/vpuri3/AbstractPDEInterfaces.jl

**Comment by PetrKryslUCSD** [comment]
Could you possibly sketch an entry for that? Or, create a pr?

**Comment by azev77** [comment]
It’s too general. Not sure
“a common interface for PDE solvers”…

**Comment by PetrKryslUCSD** [comment]
I mean: what is the two minute elevator pitch? Could you write it down?
