### ISSUE TITLE
Some packages you can add

### ISSUE THREAD

**Issue by pnavaro** [JuliaPDE/SurveyofPDEPackages#42]
This is a nice list Thanks.
I don't know in which category it goes but I have some suggestions:

- [ParallelStencil.jl](https://github.com/omlins/ParallelStencil.jl) : Package for writing high-level code for parallel high-performance stencil computations that can be deployed on both GPUs and CPUs
- [ImplicitGlobalGrid.jl](https://github.com/eth-cscs/ImplicitGlobalGrid.jl) : Almost trivial distributed parallelization of stencil-based GPU and CPU applications on a regular staggered grid
- [PencilFFTs.jl](https://github.com/jipolanco/PencilFFTs.jl) : Fast Fourier transforms of MPI-distributed Julia arrays that can be used for pseudospectral partial differential equation solvers.

Cheers

**Comment by PetrKryslUCSD** [comment]
Thanks! Would you say that these could be classified as FDM?

**Comment by pnavaro** [comment]
Yes the first two could be in FDM and the last one with Transform Methods

**Comment by pnavaro** [comment]
There is also a new one https://github.com/martinheida/HighVoronoi.jl than could classified in FVM

**Comment by PetrKryslUCSD** [comment]
FVM method: Done.

**Comment by PetrKryslUCSD** [comment]
Thanks!
