### ISSUE TITLE
Add repo stats

### ISSUE THREAD

**Issue by abmarnie** [JuliaPDE/SurveyofPDEPackages#45]
Under each section / repo, add:

![GitHub contributors](https://img.shields.io/github/contributors/owner/repo)
![GitHub closed issues](https://img.shields.io/github/issues-closed/owner/repo)
![GitHub last commit](https://img.shields.io/github/last-commit/owner/repo)
![GitHub stars](https://img.shields.io/github/stars/owner/repo)
![GitHub license](https://img.shields.io/github/license/owner/repo)

I will make a PR soon.

**Comment by PetrKryslUCSD** [comment]
Looks good! Good idea. Thanks.
